import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {MSWProvider} from "@/app/_component/MSWComponent";
import AuthSession from "@/app/_component/AuthSession";

// if (process.env.NEXT_RUNTIME === 'nodejs' && process.env.NODE_ENV !== 'production') {
//   const { server } = require('@/mocks/http')
//   server.listen()
// } //서버 컴포넌트일 때는 http.ts가 실행되어지게, 개발 모드일 시에만 적용되어지게 설정.

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode,
};
export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MSWProvider>
      <AuthSession>
        {children}
      </AuthSession>
      </MSWProvider>
      </body>
    </html>
  )
}
